apiVersion: v1
kind: Service
metadata:
  name: monolith-service
spec:
  selector:
    app: monolith-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # Assuming your app runs on port 5000 inside the container
  type: NodePort
