apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-monolith-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-app-label
  template:
    metadata:
      labels:
        app: your-app-label
    spec:
      containers:
        - name: monolith-cluster-control-plane
          image: monolith-image:tag
